<a href="https://colab.research.google.com/github/lilyblossm3-cloud/dataquest/blob/main/day1_titanic_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

url="https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

df=pd.read_csv(url)
print(f"Dataset Loaded Succesfully! Total rows and columns:{df.shape}")

df.head()

Dataset Loaded Succesfully! Total rows and columns:(891, 12)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
print("--- DATA SUMMARY & TYPES ---")
df.info()

--- DATA SUMMARY & TYPES ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
print("....Missing values per column...")
print(df.isnull().sum())
print("..Missing values with percentage..")
(df.isnull().sum()/ len(df)*100).round((1))

....Missing values per column...
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

PassengerId     0.0
Survived        0.0
Pclass          0.0
Name            0.0
Sex             0.0
Age            19.9
SibSp           0.0
Parch           0.0
Ticket          0.0
Fare            0.0
Cabin          77.1
Embarked        0.2
dtype: float64

In [ ]:
print("..Percentage of Suvived People..")
df["Survived"].value_counts()
df["Survived"].value_counts(normalize=True).round(3)

..Percentage of Suvived People..

Survived
0    0.616
1    0.384
Name: proportion, dtype: float64

In [ ]:
print("..Percentage of survived based on Sex..")
df.groupby("Sex")["Survived"].mean()

..Percentage of survived based on Sex..

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

In [ ]:
print("Based on Class")
df.groupby("Pclass")["Survived"].mean()

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

In [ ]:
numeric_cols=df.select_dtypes(include="number").columns.tolist()
categorical_cols=df.select_dtypes(include="object").columns.tolist()
print("Numeric:", numeric_cols)
print("Categorical:", categorical_cols)

Numeric: ['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare']
Categorical: ['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked']

In [ ]:
print("Correlation with numeric values")
df[numeric_cols].corr()["Survived"].sort_values(ascending=False)

Correlation with numeric values

Survived       1.000000
Fare           0.257307
Parch          0.081629
PassengerId   -0.005007
SibSp         -0.035322
Age           -0.077221
Pclass        -0.338481
Name: Survived, dtype: float64

In [ ]:
for col in categorical_cols:
  if df[col].nunique()<10:
    print(f"\n-- {col} ---")
    print(df.groupby(col)["Survived"].mean().sort_values(ascending=False))

-- Sex ---
Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

-- Embarked ---
Embarked
C    0.553571
Q    0.389610
S    0.336957
Name: Survived, dtype: float64

In [ ]:
df[["Age", "Fare", "SibSp", "Parch"]].describe()

              Age        Fare       SibSp       Parch
count  714.000000  891.000000  891.000000  891.000000
mean    29.699118   32.204208    0.523008    0.381594
std     14.526497   49.693429    1.102743    0.806057
min      0.420000    0.000000    0.000000    0.000000
25%     20.125000    7.910400    0.000000    0.000000
50%     28.000000   14.454200    0.000000    0.000000
75%     38.000000   31.000000    1.000000    0.000000
max     80.000000  512.329200    8.000000    6.000000